export const dataArray = [
    // Default Null
    { "value": "", "text": "Null"},
    // No Ban
    { "value": "none", "text": "Default"},
    // Honor of Kings CN
    { "value": "agudo", "text": "阿古朵"},
    { "value": "alessio", "text": "莱西奥"},
    { "value": "allain", "text": "亚连"},
    { "value": "angela", "text": "安琪拉"},
    { "value": "arke", "text": "阿轲"},
    { "value": "arli", "text": "公孙离"},
    { "value": "arthur (honor of kings)", "text": "亚瑟"},
    { "value": "athena", "text": "雅典娜"},
    { "value": "augran", "text": "大司命"},
    { "value": "bai qi", "text": "白起"},
    { "value": "biron", "text": "狂铁"},
    { "value": "cai yan", "text": "蔡文姬"},
    { "value": "chano", "text": "苍"},
    { "value": "cao cao", "text": "曹操"},
    { "value": "chang'e", "text": "嫦娥"},
    { "value": "charlotte", "text": "夏洛特"},
    { "value": "cheng yaojin", "text": "程咬金"},
    { "value": "child of the primal flow (mage)", "text": "元流之子(法师)"},
    { "value": "child of the primal flow (tank)", "text": "元流之子(坦克)"},
    { "value": "child of the primal flow (archer)", "text": "元流之子(射手)"},
    { "value": "cirrus", "text": "云中君"},
    { "value": "consort yu", "text": "虞姬"},
    { "value": "da qiao", "text": "大乔"},
    { "value": "daji", "text": "妲己"},
    { "value": "dharma", "text": "达摩"},
    { "value": "di renjie", "text": "狄仁杰"},
    { "value": "dian wei", "text": "典韦"},
    { "value": "diao chan (honor of kings)", "text": "貂蝉"},
    { "value": "dolia", "text": "朵莉亚"},
    { "value": "donghuang", "text": "东皇太一"},
    { "value": "dr. bian", "text": "扁鹊"},
    { "value": "dun", "text": "夏侯惇"},
    { "value": "dyadia", "text": "少司缘"},
    { "value": "erin", "text": "艾琳"},
    { "value": "fang", "text": "李元芳"},
    { "value": "feyd", "text": "暃"},
    { "value": "fuzi", "text": "老夫子"},
    { "value": "gan & mo", "text": "干将莫邪"},
    { "value": "gao", "text": "高渐离"},
    { "value": "garo", "text": "伽罗"},
    { "value": "ge ya", "text": "戈娅"},
    { "value": "guan yu", "text": "关羽"},
    { "value": "gui guzi", "text": "鬼谷子"},
    { "value": "han xin", "text": "韩信"},
    { "value": "haya", "text": "海月"},
    { "value": "heino", "text": "海诺"},
    { "value": "hou yi", "text": "后羿"},
    { "value": "huang zhong", "text": "黄忠"},
    { "value": "jin chan", "text": "金蝉"},
    { "value": "jing", "text": "镜"},
    { "value": "kaizer", "text": "铠"},
    { "value": "kong kong er", "text": "空空儿"},
    { "value": "kongming", "text": "诸葛亮"},
    { "value": "kui", "text": "钟馗"},
    { "value": "lady sun", "text": "孙尚香"},
    { "value": "lady zhen", "text": "甄姬"},
    { "value": "lam", "text": "澜"},
    { "value": "li bai", "text": "李白"},
    { "value": "li xin", "text": "李信"},
    { "value": "lian po", "text": "廉颇"},
    { "value": "liang", "text": "张良"},
    { "value": "liu bang", "text": "刘邦"},
    { "value": "liu bei", "text": "刘备"},
    { "value": "liu shan", "text": "刘禅"},
    { "value": "loong", "text": "敖隐"},
    { "value": "lu bu (honor of kings)", "text": "吕布"},
    { "value": "luban no.7", "text": "鲁班七号"},
    { "value": "luna", "text": "露娜"},
    { "value": "mai", "text": "不知火舞"},
    { "value": "ma chao", "text": "马超"},
    { "value": "marco polo", "text": "马可波罗"},
    { "value": "master luban", "text": "鲁班大师"},
    { "value": "mayene", "text": "姬小满"},
    { "value": "meng tian", "text": "蒙恬"},
    { "value": "meng ya", "text": "蒙犽"},
    { "value": "menki", "text": "梦奇"},
    { "value": "mi yue", "text": "芈月"},
    { "value": "milady", "text": "米莱狄"},
    { "value": "ming", "text": "明世隐"},
    { "value": "mozi", "text": "墨子"},
    { "value": "mulan", "text": "花木兰"},
    { "value": "musashi", "text": "宫本武藏"},
    { "value": "nakoruru", "text": "娜可露露"},
    { "value": "nezha", "text": "哪吒"},
    { "value": "toro (honor of kings)", "text": "牛魔"},
    { "value": "nuwa", "text": "女娲"},
    { "value": "pangu", "text": "盘古"},
    { "value": "pei", "text": "裴擒虎"},
    { "value": "prince of lanling", "text": "兰陵王"},
    { "value": "princess frost", "text": "王昭君"},
    { "value": "sakeer", "text": "桑启"},
    { "value": "shadow", "text": "影"},
    { "value": "shangguan", "text": "上官婉儿"},
    { "value": "shen mengxi", "text": "沈梦溪"},
    { "value": "shi", "text": "西施"},
    { "value": "shieldun", "text": "盾山"},
    { "value": "shouyue", "text": "百里守约"},
    { "value": "sikong zhen", "text": "司空震"},
    { "value": "sima yi", "text": "司马懿"},
    { "value": "su lie", "text": "苏烈"},
    { "value": "sun bin", "text": "孙膑"},
    { "value": "sun ce", "text": "孙策"},
    { "value": "sun wukong", "text": "孙悟空"},
    { "value": "taiyi zhenren", "text": "太乙真人"},
    { "value": "ukyo tachibana", "text": "橘右京"},
    { "value": "wu ze tian", "text": "武则天"},
    { "value": "wuyan", "text": "钟无艳"},
    { "value": "xiang yu", "text": "项羽"},
    { "value": "xiao qiao", "text": "小乔"},
    { "value": "xuance", "text": "百里玄策"},
    { "value": "yang jian", "text": "杨戬"},
    { "value": "dongfang yao", "text": "曜"},
    { "value": "yaria", "text": "瑶"},
    { "value": "ying", "text": "云缨"},
    { "value": "ying zheng", "text": "嬴政"},
    { "value": "yixing", "text": "弈星"},
    { "value": "yuan ge", "text": "元歌"},
    { "value": "yuhuan", "text": "杨玉环"},
    { "value": "zhang fei", "text": "张飞"},
    { "value": "zhao huaizhen", "text": "赵怀真"},
    { "value": "zhou yu", "text": "周瑜"},
    { "value": "zhu bajie", "text": "猪八戒"},
    { "value": "zhuangzi", "text": "庄周"},
    { "value": "zilong", "text": "赵云"},
    { "value": "ziya", "text": "姜子牙"},
    // Honor of Kings Global
    { "value": "ata", "text": "阿塔"},
    { "value": "butterfly", "text": "刀锋宝贝"},
    { "value": "fatih", "text": "法提赫"},
    { "value": "luara", "text": "卢雅娜"},
    // Arena of Valor

    // Removed Heroes
    { "value": "genghis khan", "text": "成吉思汗"}
];
